
package org.matrix_soft.sailor.soap.customers;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerServiceSoap {


    /**
     * 
     * @param sessionId
     * @param version
     * @return
     *     returns org.matrix_soft.sailor.soap.customers.CustomerServiceResult
     */
    @WebMethod(operationName = "GetCustomerList", action = "http://tempuri.org/GetCustomerList")
    @WebResult(name = "GetCustomerListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCustomerList", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.customers.GetCustomerList")
    @ResponseWrapper(localName = "GetCustomerListResponse", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.customers.GetCustomerListResponse")
    public CustomerServiceResult getCustomerList(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        String sessionId,
        @WebParam(name = "version", targetNamespace = "http://tempuri.org/")
        long version);

}
