
package org.matrix_soft.sailor.soap.units;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UnitSetService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://78.188.182.81/LogoWebService/Services/UnitSetService.asmx?WSDL")
public class UnitSetService
    extends Service
{

    private final static URL UNITSETSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNITSETSERVICE_EXCEPTION;
    private final static QName UNITSETSERVICE_QNAME = new QName("http://tempuri.org/", "UnitSetService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://78.188.182.81/LogoWebService/Services/UnitSetService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNITSETSERVICE_WSDL_LOCATION = url;
        UNITSETSERVICE_EXCEPTION = e;
    }

    public UnitSetService() {
        super(__getWsdlLocation(), UNITSETSERVICE_QNAME);
    }

    public UnitSetService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNITSETSERVICE_QNAME, features);
    }

    public UnitSetService(URL wsdlLocation) {
        super(wsdlLocation, UNITSETSERVICE_QNAME);
    }

    public UnitSetService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNITSETSERVICE_QNAME, features);
    }

    public UnitSetService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnitSetService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UnitSetServiceSoap
     */
    @WebEndpoint(name = "UnitSetServiceSoap")
    public UnitSetServiceSoap getUnitSetServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "UnitSetServiceSoap"), UnitSetServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnitSetServiceSoap
     */
    @WebEndpoint(name = "UnitSetServiceSoap")
    public UnitSetServiceSoap getUnitSetServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "UnitSetServiceSoap"), UnitSetServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNITSETSERVICE_EXCEPTION!= null) {
            throw UNITSETSERVICE_EXCEPTION;
        }
        return UNITSETSERVICE_WSDL_LOCATION;
    }

}
