
package org.matrix_soft.sailor.soap.units;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UnitSetServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnitSetServiceSoap {


    /**
     * 
     * @param sessionId
     * @param version
     * @return
     *     returns org.matrix_soft.sailor.soap.unit.UnitSetServiceResult
     */
    @WebMethod(operationName = "GetUnitSetList", action = "http://tempuri.org/GetUnitSetList")
    @WebResult(name = "GetUnitSetListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUnitSetList", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.unit.GetUnitSetList")
    @ResponseWrapper(localName = "GetUnitSetListResponse", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.unit.GetUnitSetListResponse")
    public UnitSetServiceResult getUnitSetList(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        String sessionId,
        @WebParam(name = "version", targetNamespace = "http://tempuri.org/")
        long version);

}
