
package org.matrix_soft.sailor.soap.firms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FirmServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirmServiceSoap {


    /**
     * 
     * @param password
     * @param adminUserPassword
     * @param adminUserName
     * @return
     *     returns org.matrix_soft.sailor.soap.firm.FirmServiceResult
     */
    @WebMethod(operationName = "GetFirmList", action = "http://tempuri.org/GetFirmList")
    @WebResult(name = "GetFirmListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFirmList", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.firm.GetFirmList")
    @ResponseWrapper(localName = "GetFirmListResponse", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.firm.GetFirmListResponse")
    public FirmServiceResult getFirmList(
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "adminUserName", targetNamespace = "http://tempuri.org/")
        String adminUserName,
        @WebParam(name = "adminUserPassword", targetNamespace = "http://tempuri.org/")
        String adminUserPassword);

    /**
     * 
     * @param password
     * @param adminUserPassword
     * @param adminUserName
     * @param firmNr
     * @return
     *     returns org.matrix_soft.sailor.soap.firm.FirmServiceResult
     */
    @WebMethod(operationName = "GetFirm", action = "http://tempuri.org/GetFirm")
    @WebResult(name = "GetFirmResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFirm", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.firm.GetFirm")
    @ResponseWrapper(localName = "GetFirmResponse", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.firm.GetFirmResponse")
    public FirmServiceResult getFirm(
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "adminUserName", targetNamespace = "http://tempuri.org/")
        String adminUserName,
        @WebParam(name = "adminUserPassword", targetNamespace = "http://tempuri.org/")
        String adminUserPassword,
        @WebParam(name = "firmNr", targetNamespace = "http://tempuri.org/")
        int firmNr);

}
