
package org.matrix_soft.sailor.soap.firms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FirmService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://78.188.182.81/LogoWebService/Services/FirmService.asmx?WSDL")
public class FirmService
    extends Service
{

    private final static URL FIRMSERVICE_WSDL_LOCATION;
    private final static WebServiceException FIRMSERVICE_EXCEPTION;
    private final static QName FIRMSERVICE_QNAME = new QName("http://tempuri.org/", "FirmService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://78.188.182.81/LogoWebService/Services/FirmService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIRMSERVICE_WSDL_LOCATION = url;
        FIRMSERVICE_EXCEPTION = e;
    }

    public FirmService() {
        super(__getWsdlLocation(), FIRMSERVICE_QNAME);
    }

    public FirmService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIRMSERVICE_QNAME, features);
    }

    public FirmService(URL wsdlLocation) {
        super(wsdlLocation, FIRMSERVICE_QNAME);
    }

    public FirmService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIRMSERVICE_QNAME, features);
    }

    public FirmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirmService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FirmServiceSoap
     */
    @WebEndpoint(name = "FirmServiceSoap")
    public FirmServiceSoap getFirmServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "FirmServiceSoap"), FirmServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirmServiceSoap
     */
    @WebEndpoint(name = "FirmServiceSoap")
    public FirmServiceSoap getFirmServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "FirmServiceSoap"), FirmServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIRMSERVICE_EXCEPTION!= null) {
            throw FIRMSERVICE_EXCEPTION;
        }
        return FIRMSERVICE_WSDL_LOCATION;
    }

}
