
package org.matrix_soft.sailor.soap.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServiceSoap {


    /**
     * 
     * @param sessionId
     * @param order
     * @return
     *     returns org.matrix_soft.sailor.soap.order.ServiceResult
     */
    @WebMethod(operationName = "CreateSaleOrder", action = "http://tempuri.org/CreateSaleOrder")
    @WebResult(name = "CreateSaleOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateSaleOrder", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.order.CreateSaleOrder")
    @ResponseWrapper(localName = "CreateSaleOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.matrix_soft.sailor.soap.order.CreateSaleOrderResponse")
    public ServiceResult createSaleOrder(
        @WebParam(name = "sessionId", targetNamespace = "http://tempuri.org/")
        String sessionId,
        @WebParam(name = "order", targetNamespace = "http://tempuri.org/")
        Order order);

}
