CREATE TABLE COMPANY (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  VERSION INT NOT NULL DEFAULT 0,
  PRIMARY KEY(ID)
);

CREATE TABLE USERS (
  ID INT NOT NULL AUTO_INCREMENT,
  USER_TYPE VARCHAR(20) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  SURNAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50),
  USERNAME VARCHAR(45) NOT NULL UNIQUE,
  PASSWORD VARCHAR(60) NOT NULL,
  USER_STATUS VARCHAR (20) NOT NULL DEFAULT 'ACTIVE',
  COMPANY INT NOT NULL,
  VERSION INT NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  CONSTRAINT FK_USER_COMPANY FOREIGN KEY (COMPANY) REFERENCES COMPANY (ID)
);

CREATE TABLE LICENSES (
  ID INT NOT NULL AUTO_INCREMENT,
  SERIAL_NUMBER VARCHAR(10) NOT NULL,
  OWNER INT NOT NULL,
  USER_COUNT INT NOT NULL,
  LICENSE_STATUS VARCHAR(20) NOT NULL,
  VERSION INT NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  CONSTRAINT FK_LICENSE_USER FOREIGN KEY (OWNER) REFERENCES USERS (ID)
);